### ISSUE TITLE
Drawing problem

### ISSUE THREAD

**Issue by crow1814** [egk696/SimpleSMTScheduler#1]
Hi, egk696
I have used your simpleSMTScheudler to generate a schedule, but there are some troubles with drawing pictures.
The steps are:
Enter the csv file for the tasks to be scheduled: examples/simple_tasks.csv
Enter the WCET allocation gap between activations: 50
Enter the number of hyper periods to be plotted: 2
Enable statistics (Yes/No)? No
Then I can obtain a schedule, but the trouble is:
`  File "I:\engineering\project\virtual\lib\site-packages\matplotlib\axes\_base.py", line 3326, in set_xlim
    reverse = left > right
TypeError: '>' not supported between instances of 'int' and 'list'`

**Comment by egk696** [comment]
Hi, and thanks for finding the issue. I am not using the interactive mode often and I must have missed it. More issues or ideas for improvement are always welcome 👍
