### ISSUE TITLE
Online app mentioned in README is down

### ISSUE THREAD

**Issue by ephraim271** [egk696/SimpleSMTScheduler#4]
```
A simple SMT-based schedule generator for cyclic executives real-time tasks

To quickly use the application online please visit us at: [Simple Cyclic Scheduler Online](https://simplescheduleronline.herokuapp.com/)
```

**Comment by egk696** [comment]
Hi, yes this happened because it was not getting enough traffic so to free up space Heroku automatically stops hosting our app. But if anyone wants to host the scheduler somewhere else, it's quite simple to upload it to any server since it's built with Docker,
