### ISSUE TITLE
Where can I learn about the math behind the implementation? 

### ISSUE THREAD

**Issue by ephraim271** [egk696/SimpleSMTScheduler#5]
First off, thanks a lot for this tool, its extremely useful!
Looking for some documentation/literature/paper on how it works, out of curiosity. Would appreciate any resources.

**Comment by egk696** [comment]
I am glad someone else found it useful to use besides me when I made it! So this was developed as part of a research so you can find the theory and usage in the following two papers:
- [Synchronizing Real-Time Tasks in Time-Triggered Networks](https://ieeexplore.ieee.org/abstract/document/9470242)
- [Evaluating a Time-Triggered Runtime System by Distributing a Flight Controller](https://ieeexplore.ieee.org/abstract/document/9613679)

But in general it uses constraint programming rules to derive the schedule. The math behind how the constraint is solved is based on a [Z3 SMT](https://www.microsoft.com/en-us/research/project/z3-3/).

**Comment by ephraim271** [comment]
Thanks! Will checkout those papers.
